project_name: nginx-errors
builds:
  - main: .
    binary: nginx-errors
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
    goos:
      - linux
      - darwin
archives:
  - files:
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
